[2025-10-24T00:39:42.800+0200] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-24T00:39:42.842+0200] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_hourly_refresh.run_dbt_models manual__2025-10-23T22:39:41.184746+00:00 [queued]>
[2025-10-24T00:39:42.864+0200] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_hourly_refresh.run_dbt_models manual__2025-10-23T22:39:41.184746+00:00 [queued]>
[2025-10-24T00:39:42.865+0200] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-10-24T00:39:42.898+0200] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): run_dbt_models> on 2025-10-23 22:39:41.184746+00:00
[2025-10-24T00:39:42.916+0200] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dbt_hourly_refresh', 'run_dbt_models', 'manual__2025-10-23T22:39:41.184746+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/dbt_hourly_refresh_dag.py', '--cfg-path', '/tmp/tmpj8phl7s8']
[2025-10-24T00:39:42.924+0200] {standard_task_runner.py:105} INFO - Job 19: Subtask run_dbt_models
[2025-10-24T00:39:42.926+0200] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=675) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-24T00:39:42.928+0200] {standard_task_runner.py:72} INFO - Started process 676 to run task
[2025-10-24T00:39:43.089+0200] {task_command.py:467} INFO - Running <TaskInstance: dbt_hourly_refresh.run_dbt_models manual__2025-10-23T22:39:41.184746+00:00 [running]> on host 0552639bb6f4
[2025-10-24T00:39:43.418+0200] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Aliostadi' AIRFLOW_CTX_DAG_ID='dbt_hourly_refresh' AIRFLOW_CTX_TASK_ID='run_dbt_models' AIRFLOW_CTX_EXECUTION_DATE='2025-10-23T22:39:41.184746+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-23T22:39:41.184746+00:00'
[2025-10-24T00:39:43.420+0200] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-24T00:39:43.534+0200] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-24T00:39:43.535+0200] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/dbt_project && dbt run']
[2025-10-24T00:39:43.553+0200] {subprocess.py:86} INFO - Output:
[2025-10-24T00:39:48.619+0200] {subprocess.py:93} INFO - [0m22:39:48  Running with dbt=1.8.5
[2025-10-24T00:39:49.300+0200] {subprocess.py:93} INFO - [0m22:39:49  Registered adapter: postgres=1.8.2
[2025-10-24T00:39:49.636+0200] {subprocess.py:93} INFO - [0m22:39:49  Unable to do partial parsing because of a version mismatch
[2025-10-24T00:39:51.606+0200] {subprocess.py:93} INFO - [0m22:39:51  [[33mWARNING[0m]: Deprecated functionality
[2025-10-24T00:39:51.612+0200] {subprocess.py:93} INFO - The `tests` config has been renamed to `data_tests`. Please see
[2025-10-24T00:39:51.613+0200] {subprocess.py:93} INFO - https://docs.getdbt.com/docs/build/data-tests#new-data_tests-syntax for more
[2025-10-24T00:39:51.613+0200] {subprocess.py:93} INFO - information.
[2025-10-24T00:39:51.986+0200] {subprocess.py:93} INFO - [0m22:39:51  Encountered an error:
[2025-10-24T00:39:51.986+0200] {subprocess.py:93} INFO - [Errno 13] Permission denied: '/opt/***/dbt_project/target/partial_parse.msgpack'
[2025-10-24T00:39:51.988+0200] {subprocess.py:93} INFO - [0m22:39:51  Traceback (most recent call last):
[2025-10-24T00:39:51.989+0200] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/cli/requires.py", line 138, in wrapper
[2025-10-24T00:39:51.989+0200] {subprocess.py:93} INFO -     result, success = func(*args, **kwargs)
[2025-10-24T00:39:51.989+0200] {subprocess.py:93} INFO -                       ^^^^^^^^^^^^^^^^^^^^^
[2025-10-24T00:39:51.989+0200] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/cli/requires.py", line 101, in wrapper
[2025-10-24T00:39:51.989+0200] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2025-10-24T00:39:51.990+0200] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^
[2025-10-24T00:39:51.990+0200] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/cli/requires.py", line 218, in wrapper
[2025-10-24T00:39:51.990+0200] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2025-10-24T00:39:51.990+0200] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^
[2025-10-24T00:39:51.990+0200] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/cli/requires.py", line 247, in wrapper
[2025-10-24T00:39:51.990+0200] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2025-10-24T00:39:51.991+0200] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^
[2025-10-24T00:39:51.991+0200] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/cli/requires.py", line 294, in wrapper
[2025-10-24T00:39:51.991+0200] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2025-10-24T00:39:51.991+0200] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^
[2025-10-24T00:39:51.992+0200] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/cli/requires.py", line 320, in wrapper
[2025-10-24T00:39:51.992+0200] {subprocess.py:93} INFO -     ctx.obj["manifest"] = parse_manifest(
[2025-10-24T00:39:51.992+0200] {subprocess.py:93} INFO -                           ^^^^^^^^^^^^^^^
[2025-10-24T00:39:51.992+0200] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/parser/manifest.py", line 1898, in parse_manifest
[2025-10-24T00:39:51.992+0200] {subprocess.py:93} INFO -     manifest = ManifestLoader.get_full_manifest(
[2025-10-24T00:39:51.993+0200] {subprocess.py:93} INFO -                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-10-24T00:39:51.993+0200] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/parser/manifest.py", line 330, in get_full_manifest
[2025-10-24T00:39:51.993+0200] {subprocess.py:93} INFO -     manifest = loader.load()
[2025-10-24T00:39:51.993+0200] {subprocess.py:93} INFO -                ^^^^^^^^^^^^^
[2025-10-24T00:39:51.994+0200] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/parser/manifest.py", line 525, in load
[2025-10-24T00:39:51.994+0200] {subprocess.py:93} INFO -     self.write_manifest_for_partial_parse()
[2025-10-24T00:39:51.994+0200] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/parser/manifest.py", line 813, in write_manifest_for_partial_parse
[2025-10-24T00:39:51.994+0200] {subprocess.py:93} INFO -     with open(path, "wb") as fp:
[2025-10-24T00:39:51.995+0200] {subprocess.py:93} INFO -          ^^^^^^^^^^^^^^^^
[2025-10-24T00:39:51.995+0200] {subprocess.py:93} INFO - PermissionError: [Errno 13] Permission denied: '/opt/***/dbt_project/target/partial_parse.msgpack'
[2025-10-24T00:39:51.995+0200] {subprocess.py:93} INFO - 
[2025-10-24T00:39:52.430+0200] {subprocess.py:97} INFO - Command exited with return code 2
[2025-10-24T00:39:52.532+0200] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-10-24T00:39:52.550+0200] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_hourly_refresh, task_id=run_dbt_models, run_id=manual__2025-10-23T22:39:41.184746+00:00, execution_date=20251023T223941, start_date=20251023T223942, end_date=20251023T223952
[2025-10-24T00:39:52.585+0200] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-24T00:39:52.586+0200] {standard_task_runner.py:124} ERROR - Failed to execute job 19 for task run_dbt_models (Bash command failed. The command returned a non-zero exit code 2.; 676)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-10-24T00:39:52.657+0200] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-10-24T00:39:52.684+0200] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-24T00:39:52.687+0200] {local_task_job_runner.py:245} INFO - ::endgroup::
